```{r}
logs <- read_csv("https://dwillis.github.io/sports-data-files/wbblogs24.csv")
```

```{r}
difflogs <- logs |> 
  mutate(Differential = TeamScore - OpponentScore) |> 
  group_by(TeamFullName) |> 
  mutate(CumDiff = cumsum(Differential))
```

```{r}
bigdiff <- difflogs |> filter(Conference == "Big Ten WBB")
```

```{r}
ggplot() + geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team))
```
```{r}
ggplot() + geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team, color=Team))
```
```{r}
umd <- bigdiff |> filter(Team == "Maryland")
ill <- bigdiff |> filter(Team == "Illinois")
ggplot() + 
  geom_step(data=bigdiff, aes(x=Date, y=CumDiff, group=Team), color="light grey") +
  geom_step(data=umd, aes(x=Date, y=CumDiff, group=Team), color="red") + 
  geom_step(data=ill, aes(x=Date, y=CumDiff, group=Team), color="orange") +
  annotate("text", x=(as.Date("2023-12-10")), y=300, label="Illinois") +
  annotate("text", x=(as.Date("2024-02-01")), y=150, label="Maryland") +
  labs(
    x="Date", 
    y="Cumulative Point Differential", 
    title="Maryland's Uphill Climb, Illinois Hits Plateau", 
    subtitle="The Terps were middle of the pack in point differential.", 
    caption="Source: Sports-Reference.com | By Derek Willis") +
  theme_minimal()
```

