#WBB Notebook

```{r}
library(tidyverse)
library(ggrepel)
```

```{r}
teams <- read_csv("https://dwillis.github.io/sports-data-files/wbbstats25.csv")
```

```{r}
umd <- teams |> filter(School == "Maryland")
unbeaten <- teams|> filter(OverallLosses == 0)
big_ten <- teams |> filter(School %in% c('Illinois', 'Indiana', 'Iowa', 'Michigan', 'Michigan State', 'Ohio State', 'Minnesota', 'Nebraska', 'Northwestern', 'Rutgers', 'Southern California', 'UCLA', 'Oregon', 'Washington', 'Maryland'))
avg_srs <- teams |> filter(!is.na(OverallSRS)) |> summarize(mean(OverallSRS)) |> pull(1)
avg_sos <- teams |> filter(!is.na(OverallSOS)) |> summarize(mean(OverallSOS)) |> pull(1)
ggplot() +
  geom_point(data = unbeaten, aes(x = OverallSRS, y = OverallSOS), color = "green") +
  geom_point(data = big_ten, aes(x = OverallSRS, y= OverallSOS), color = "blue")
  geom_point(data = umd, aes(x = OverallSRS, y = OverallSOS), color = "red") +
  geom_vline(xintercept = avg_srs) + 
  geom_hline(yintercept = avg_sos) +
  geom_text_repel(
    data=unbeaten, 
    aes(x=OverallSRS, y=OverallSOS, label=School)
  )

```

```{r}

```


```{r}
teamzscore <- teamtotals |> 
  mutate(
    FGzscore = as.numeric(scale(FGAvg, center = TRUE, scale = TRUE)),
    RebZscore = as.numeric(scale(ReboundAvg, center = TRUE, scale = TRUE)),
    OppZscore = as.numeric(scale(OppFGAvg, center = TRUE, scale = TRUE)) * -1,
    OppRebZScore = as.numeric(scale(OffRebAvg, center = TRUE, scale = TRUE)) * -1,
    TotalZscore = FGzscore + RebZscore + OppZscore + OppRebZScore
  )  
teamzscore
```
```{r}
teamzscore |> arrange(desc(TotalZscore))
```
```{r}
teamzscore |> 
  filter(Conference == "Big Ten WBB") |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```
```{r}
powerfive_plus_one <- c("SEC WBB", "Big Ten WBB", "Pac-12 WBB", "Big 12 WBB", "ACC WBB", "Big East WBB")
teamzscore |> 
  filter(Conference %in% powerfive_plus_one) |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```

